version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: harmalh-opencode_web_1
      APP_PORT: 80

  web:
    image: nginx:1.25-alpine
    restart: on-failure
    init: true
    volumes:
      - ${APP_DATA_DIR}/www:/usr/share/nginx/html:ro
